### ISSUE TITLE
First question

### ISSUE THREAD

**Issue by EvaZ7** [PipHarsveld/BrainBattle#15]
Bovenaan de vraag staat steeds dat je nog bij de eerste vraag bent ook al klik je verder. Misschien dat als je verder klikt dat er vraag 2 staat, je kan met JS een clickcount(er) maken hiervoor

**Comment by PipHarsveld** [comment]
Helaas geen tijd om een clickcounter te maken, maar heb de zin nu wel verwijderd om zo verwarring te voorkomen
