### ISSUE TITLE
De berichten lopen

### ISSUE THREAD

**Issue by Inevdhoven** [PipHarsveld/BrainBattle#3]
Wanneer je een bericht stuurt krijg je het bericht dubbel. Wanneer iemand anders dan een bericht terug stuurt komt het bericht vorige bericht met het nieuwe bericht binnen. Wanneer je even wacht dan komen de berichten meerdere keren.

**Comment by Inevdhoven** [comment]
Hier een screenshot hoe het eruit ziet: https://gyazo.com/dba342774259c863e82bdfe31b9d9192

**Comment by PipHarsveld** [comment]
Om eerlijk te zijn heb ik geen idee hoe, maar ik heb dit probleem nu niet meer!
